spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB-OAUTH2-CLIENT-ID}
            client-secret: ${GITHUB-OAUTH2-CLIENT-SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          google:
            client-id: ${GOOGLE-OAUTH2-CLIENT-ID}
            client-secret: ${GOOGLE-OAUTH2-CLIENT-SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"